### ISSUE TITLE
core4.util.email.RoleEmail errors when creating User or Role

### ISSUE THREAD

**Issue by basteiz** [plan-net/core4#142]
```javascript
chist -i 5de7a8e12e019559123561c3
2019-12-04 13:39:14 INFO     core4@worker1.spm core4.util.email.RoleEmail@5de7a8e12e019559123561c3: start execution
2019-12-04 13:39:14 CRITICAL core4@worker1.spm core4.util.email.RoleEmail@5de7a8e12e019559123561c3: done execution with [error] after [16] sec. and [0] attempts to go: KeyError('contact',)
Traceback (most recent call last):

  File "/srv/core4/home/core4/.venv/lib/python3.5/site-packages/core4/queue/process.py", line 84, in start
    job.execute(**job.args)

  File "/srv/core4/home/core4/.venv/lib/python3.5/site-packages/core4/util/email.py", line 124, in execute
    contact_email=self.config.api.contact)

KeyError: 'contact'

```

**Comment by MarkusKral** [comment]
Hi,

this seems to have been introduced by @m-rau with commit fc5614ea39204b2ef5df9796cfccd725ffdae1ff

The commit moves the contact-setting form the api section to user_setting section.

@m-rau: Can you confirm this? 

Currently we are only testing whether the Email-job has been enqueued:

test_auth::test_password_reset

How do we test the successful sending of an email even though the tests may run "vanilla" without any email-account setup yet?

**Comment by m-rau** [comment]
has been fixed.
